// src/app/modules/about/about.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-about',
	templateUrl: './about.component.html',
	styleUrls: ['./about.component.sass'],
})
export class AboutComponent implements OnInit {
	constructor() {}

	ngOnInit() {}
}

<div class="content">
	<div className="about-container">
		<div className="text">⚑ b. 1991 Los Angeles, California</div>
		<div className="text">⚑ Currently lives and works in Portland, Oregon</div>
		<div className="text">⚑ Software Engineer</div>
	</div>
</div>

// src/views/About.tsx
import React from 'react';
import './AboutStyles.scss';

const About = () => {
	return (
		<div className="about-text-container">
			<div className="text">
				<span className="unicode">&#x261E;</span> b. 1991 Los Angeles, California
			</div>
			<div className="text">
				<span className="unicode">&#x263B;</span> Currently lives and works in Portland, Oregon
			</div>
			<div className="text">
				<span className="unicode">&#x2668;</span> Software Engineer
			</div>
		</div>
	);
};

export default About;
